include("${CMAKE_CURRENT_LIST_DIR}/id.cmake")

if (MSVC)
    if (MSVC60)
	set(ICU_TOOLSET "v60")
    elseif(MSVC70)
	set(ICU_TOOLSET "v70")
    elseif(MSVC71)
	set(ICU_TOOLSET "v71")
    elseif(MSVC80)
	set(ICU_TOOLSET "v80")
    elseif(MSVC90)
	set(ICU_TOOLSET "v90")
    elseif(MSVC10)
	set(ICU_TOOLSET "v100")
    elseif(MSVC11)
	set(ICU_TOOLSET "v110")
    elseif(MSVC12)
	set(ICU_TOOLSET "v120")
    elseif(MSVC13)
	set(ICU_TOOLSET "v130")
    elseif(MSVC14)
	set(ICU_TOOLSET "v140")
    else()
	cmut_fatal("You try to build ${package} on platform not ahndle by this script. fix it and try again.")
	return()
    endif()
endif()
