include("${CMAKE_CURRENT_LIST_DIR}/id.cmake")



byd__package__add_component(${package} CppParser)
byd__package__add_component(${package} Crypto)
byd__package__add_component(${package} Data)
byd__package__add_component(${package} Data_MySQL)
byd__package__add_component(${package} Data_ODBC)
byd__package__add_component(${package} Data_SQLite)
byd__package__add_component(${package} JSON)
byd__package__add_component(${package} MongoDB)
byd__package__add_component(${package} Net)
byd__package__add_component(${package} NetSSL)
byd__package__add_component(${package} PageCompiler)
byd__package__add_component(${package} PageCompiler_File2Page)
byd__package__add_component(${package} PDF)
byd__package__add_component(${package} SevenZip)
byd__package__add_component(${package} Util)
byd__package__add_component(${package} XML)
byd__package__add_component(${package} Zip)
