set(QT5_COMPONENTS
    qt3d
    qtactiveqt
    qtandroidextras
    qtbase
    qtcanvas3d
    qtcharts
    qtconnectivity
    qtdatavis3d
    qtdeclarative
    qtdoc
    qtgamepad
    qtgraphicaleffects
    qtimageformats
    qtlocation
    qtmacextras
    qtmultimedia
    qtnetworkauth
    qtpurchasing
    qtquickcontrols
    qtquickcontrols2
    qtremoteobjects
    qtscript
    qtscxml
    qtsensors
    qtserialbus
    qtserialport
    qtspeech
    qtsvg
    qttools
    qttranslations
    qtvirtualkeyboard
    qtwayland
    qtwebchannel
    qtwebengine
    qtwebsockets
    qtwebview
    qtwinextras
    qtx11extras
    qtxmlpatterns
)
