include("${CMAKE_CURRENT_LIST_DIR}/id.cmake")



byd__package__add_component(${package} atomic          VERSION 1.53.0)
byd__package__add_component(${package} chrono          VERSION 1.47.0)
byd__package__add_component(${package} container       VERSION 1.56.0)
byd__package__add_component(${package} context         VERSION 1.51.0)
byd__package__add_component(${package} coroutine       VERSION 1.53.0)
byd__package__add_component(${package} coroutine2      VERSION 1.60.0)
byd__package__add_component(${package} date_time       VERSION 1.29.0)
byd__package__add_component(${package} exception       VERSION 1.36.0)
byd__package__add_component(${package} fiber           VERSION 1.62.0)
byd__package__add_component(${package} filesystem      VERSION 1.30.0)
byd__package__add_component(${package} graph           VERSION 1.18.0)
byd__package__add_component(${package} graph_parallel  VERSION 1.18.0)
byd__package__add_component(${package} iostreams       VERSION 1.33.0)
byd__package__add_component(${package} locale          VERSION 1.48.0)
byd__package__add_component(${package} log             VERSION 1.54.0)
byd__package__add_component(${package} math            VERSION 1.23.0)
byd__package__add_component(${package} metaparse       VERSION 1.61.0)
byd__package__add_component(${package} mpi             VERSION 1.35.0)
byd__package__add_component(${package} program_options VERSION 1.32.0)
byd__package__add_component(${package} python          VERSION 1.19.0)
byd__package__add_component(${package} random          VERSION 1.15.0)
byd__package__add_component(${package} regex           VERSION 1.18.0)
byd__package__add_component(${package} serialization   VERSION 1.32.0)
byd__package__add_component(${package} signals         VERSION 1.29.0)
byd__package__add_component(${package} system          VERSION 1.35.0)
byd__package__add_component(${package} test            VERSION 1.21.0)
byd__package__add_component(${package} thread          VERSION 1.25.0)
byd__package__add_component(${package} timer           VERSION 1.9.0)
byd__package__add_component(${package} type_erasure    VERSION 1.60.0)
byd__package__add_component(${package} wave            VERSION 1.33.0)
