
byd__Qt5__configure__add_arg_system_or_qt(${package} zlib)
byd__Qt5__configure__add_arg_if_dependency_is_added(${package} mtdev)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} journald)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} syslog)
byd__Qt5__configure__add_arg_system_or_qt(${package} libpng)
byd__Qt5__configure__add_arg_system_or_qt(${package} libjpeg libjpeg_turbo)
byd__Qt5__configure__add_arg_system_or_qt(${package} doubleconversion)
byd__Qt5__configure__add_arg_system_or_qt(${package} freetype)
byd__Qt5__configure__add_arg_system_or_qt(${package} harfbuzz)
byd__Qt5__configure__add_arg_if_dependency_is_added(${package} openssl OpenSSL)
byd__Qt5__configure__add_arg_if_dependency_is_added(${package} libproxy)
byd__Qt5__configure__add_arg_system_or_qt(${package} pcre)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} pulseaudio)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} alsa)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} gtk)

#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} cups)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} iconv)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} evdev)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} tslib)
byd__Qt5__configure__add_arg_if_dependency_is_added(${package} icu)
byd__Qt5__configure__add_arg_if_dependency_is_added(${package} fontconfig)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} dbus)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} xcb)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} eglfs)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} kms)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} gbm)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} directfb)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} linuxfb)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} libinput)
#byd__Qt5__configure__add_arg_if_dependency_is_added(${package} gstreamer)
