include("${CMAKE_CURRENT_LIST_DIR}/id.cmake")



byd__package__add_component(${package} composite)
byd__package__add_component(${package} damage)
byd__package__add_component(${package} dpms)
byd__package__add_component(${package} dri2)
byd__package__add_component(${package} dri3)
byd__package__add_component(${package} glx)
byd__package__add_component(${package} present)
byd__package__add_component(${package} randr)
byd__package__add_component(${package} record)
byd__package__add_component(${package} render)
byd__package__add_component(${package} resource)
byd__package__add_component(${package} screensaver)
byd__package__add_component(${package} shape)
byd__package__add_component(${package} shm)
byd__package__add_component(${package} sync)
byd__package__add_component(${package} xevie)
byd__package__add_component(${package} xfixes)
byd__package__add_component(${package} xfree86-dri)
byd__package__add_component(${package} xinerama)
byd__package__add_component(${package} xinput)
byd__package__add_component(${package} xkb)
byd__package__add_component(${package} xprint)
byd__package__add_component(${package} selinux)
byd__package__add_component(${package} xtest)
byd__package__add_component(${package} xv)
byd__package__add_component(${package} xvmc)
