


if(MSVC)
    set(BOOST_TOOLSET_NAME msvc)
    if (MSVC60)
        set(BOOST_TOOLSET_VERSION "6.0")
    elseif(MSVC70)
        set(BOOST_TOOLSET_VERSION "7.0")
    elseif(MSVC71)
        set(BOOST_TOOLSET_VERSION "7.1")
    elseif(MSVC80)
        set(BOOST_TOOLSET_VERSION "8.0")
    elseif(MSVC90)
        set(BOOST_TOOLSET_VERSION "9.0")
    elseif(MSVC10)
        set(BOOST_TOOLSET_VERSION "10.0")
    elseif(MSVC11)
        set(BOOST_TOOLSET_VERSION "11.0")
    elseif(MSVC12)
        set(BOOST_TOOLSET_VERSION "12.0")
    elseif(MSVC13)
        set(BOOST_TOOLSET_VERSION "13.0")
    elseif(MSVC14)
        set(BOOST_TOOLSET_VERSION "14.0")
    endif()
elseif(BORLAND)
    set(BOOST_TOOLSET_NAME "bcb")
    set(BOOST_TOOLSET_NAME "bcb")
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(BOOST_TOOLSET_NAME "gcc")
elseif(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    set(BOOST_TOOLSET_NAME "clang")
else()
    string(TOLOWER "${CMAKE_CXX_COMPILER_ID}" BOOST_TOOLSET_NAME)
    if(CMAKE_CXX_COMPILER_VERSION MATCHES "([0-9]+)[.]([0-9]+)")
        set(BOOST_TOOLSET_VERSION "${CMAKE_MATCH_1}${CMAKE_MATCH_2}")
    endif()
endif()


set(BOOST_TOOLSET "${BOOST_TOOLSET_NAME}")
if(BOOST_TOOLSET_VERSION)
    set(BOOST_TOOLSET "${BOOST_TOOLSET}-${BOOST_TOOLSET_VERSION}")
endif()
    