


if (MSVC60)
    set(BOOST_TOOLSET "msvc-6.0")
elseif(MSVC70)
    set(BOOST_TOOLSET "msvc-7.0")
elseif(MSVC71)
    set(BOOST_TOOLSET "msvc-7.1")
elseif(MSVC80)
    set(BOOST_TOOLSET "msvc-8.0")
elseif(MSVC90)
    set(BOOST_TOOLSET "msvc-9.0")
elseif(MSVC10)
    set(BOOST_TOOLSET "msvc-10.0")
elseif(MSVC11)
    set(BOOST_TOOLSET "msvc-11.0")
elseif(MSVC12)
    set(BOOST_TOOLSET "msvc-12.0")
elseif(MSVC13)
    set(BOOST_TOOLSET "msvc-13.0")
elseif(MSVC14)
    set(BOOST_TOOLSET "msvc-14.0")
elseif(MSVC)
    set(BOOST_TOOLSET "msvc")
elseif(BORLAND)
    set(BOOST_TOOLSET "bcb")
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(BOOST_TOOLSET "gcc")
elseif(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    set(BOOST_TOOLSET "clang")
else()
    string(TOLOWER "${CMAKE_CXX_COMPILER_ID}" BOOST_TOOLSET)
    if(CMAKE_CXX_COMPILER_VERSION MATCHES "([0-9]+)[.]([0-9]+)")
        set(BOOST_TOOLSET "${BOOST_TOOLSET}${CMAKE_MATCH_1}${CMAKE_MATCH_2}")
    endif()
endif()
