
include("${BYD_ROOT}/cmake/modules/option/byd__option__build_shared_libs.cmake")
include("${BYD_ROOT}/cmake/modules/option/byd__option__build_testing.cmake")
include("${BYD_ROOT}/cmake/modules/option/byd__option__force_build.cmake")
include("${BYD_ROOT}/cmake/modules/option/byd__option__jobs.cmake")
include("${BYD_ROOT}/cmake/modules/option/byd__option__local_repo.cmake")
include("${BYD_ROOT}/cmake/modules/option/byd__option__log_step.cmake")
include("${BYD_ROOT}/cmake/modules/option/byd__option__prefix.cmake")
include("${BYD_ROOT}/cmake/modules/option/byd__option__remote_repo.cmake")
include("${BYD_ROOT}/cmake/modules/option/byd__option__upload_archive.cmake")
