include("${BYD_ROOT}/cmake/modules/package/byd__package__component.cmake")
include("${BYD_ROOT}/cmake/modules/package/byd__package__dependency.cmake")
include("${BYD_ROOT}/cmake/modules/package/byd__package__info.cmake")
include("${BYD_ROOT}/cmake/modules/package/byd__package__is_build.cmake")
include("${BYD_ROOT}/cmake/modules/package/byd__package__property.cmake")
